### ISSUE TITLE
How to map code coverage about angular template using istanbul

### ISSUE THREAD

**Issue by mestihudson** [edumserrano/monocart-code-coverage-demo#1]
Hi, Eduardo.

Congratulations on your great work.
I am following your steps to cover my angular project; it was an amazing place to start.
I could see that using monocart you have to cover HTML templates, but, like me, you did not with Istanbul.
My question: haven't you just updated the repo or you even tried?

Thank you.

**Comment by edumserrano** [comment]
Hi Hudson,

You are correct, when I use the code coverage option built-in to the monocart library I do get code coverage for HTML files as well as the TS files. However, I do NOT get code coverage for HTML files when using babel+istanbul.

I did NOT try to get the HTML coverage showing when using babel+istanbul so I'm afraid I don't have any tips to help you out.
