### ISSUE TITLE
Tests don't run

### ISSUE THREAD

**Issue by yuriy-bezrukov** [edumserrano/monocart-code-coverage-demo#2]
hello @edumserrano  

tests don't run

test-istanbu

![image](https://github.com/edumserrano/monocart-code-coverage-demo/assets/11812321/1e9657de-8315-41e1-9c00-4493471c6a00)

test-monocart

![image](https://github.com/edumserrano/monocart-code-coverage-demo/assets/11812321/b94ac077-df29-438c-add5-98eeb6fb0859)

**Comment by yuriy-bezrukov** [comment]
1. need install browsers `npx playwright install`
2. change ports `const _webServerPort = 4200;`

And everything worked!

Thank you for your work, it saved a lot of time for many people =)

**Comment by edumserrano** [comment]
You are right, I should have mentioned that in the README. I've updated it accordingly with e7aba936e311d565f6842ec7ff3bc7ad2c5f8160.

Thank you for the feedback.
